builds:
  - binary: tanker
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: >
      -X main.BuildDate={{.Date}}
      -X main.GitCommit={{.Commit}}
      -X main.GitBranch={{.Env.GIT_BRANCH}}
      -X main.GitUpstream={{.Env.GIT_UPSTREAM}}
      -X main.Version={{.Version}}

dist: build/release

git:
  short_hash: true

release:
  draft: true

env_files:
  github_token: .github_token

archive:
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
  wrap_in_directory: true
